version: '3.8'

services:
  nginx:
    image: openresty/openresty:1.21.4.1-0-alpine
    #image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - ./lua-scripts:/etc/nginx/lua-scripts
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - redis
      - ldap

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "mycompany.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      LDAP_TLS: "false"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap-init:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: ["--loglevel", "debug", "--copy-service"]

volumes:
  redis_data:
  ldap_data:
  ldap_config:
