site_name: Burgonet Gateway Documentation

nav:
  - Home: index.md
  - Technical Overview: technical.md
  - Screenshots: screenshots.md
  - About: about.md

theme:
  name: readthedocs
  analytics:
    gtag: GTM-TSWFRGBR

plugins:
  - search
  - mermaid2





